name: ainavi
description: 'This is a job-hunting support app utilizing AI.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # 状態管理
  provider:
  # dotenv
  flutter_dotenv:
  # shared_preferences利用
  shared_preferences:
  # splash画面(起動時ロード画面)
  flutter_native_splash: ^2.3.1
  # アプリアイコン
  flutter_launcher_icons: ^0.13.1
  # タイマー
  stop_watch_timer:
  # sqLite接続
  sqflite:
  # OS pathアクセス
  path:
  # 画面アイコン
  cupertino_icons: ^1.0.2
  # 多言語対応
  intl: ^0.17.0
  # チャットUI
  flutter_chat_ui: ^1.6.12
  flutter_chat_types:
  # カメラ操作(カスタム可能)
  camera:
  # 画像撮影・取得(組み込みなのでカスタム不可)
  image_picker: ^1.0.4
  file_picker:
  # AWS接続
  amazon_cognito_identity_dart_2:
  # http接続
  http:
  # http接続_old
  dio:
  # 音声関連
  record:
  audioplayers:
  path_provider:
  # chatGPT用open-ai
  dart_openai: ^4.0.0
  # ファイル
  open_filex:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_lint: ^1.1.2
  custom_lint: 
  riverpod_generator: ^2.0.0
  build_runner: ^2.3.3


# view splash config
flutter_native_splash:
  image: "assets/images/AINavi.png"
  color: "#FFFFFF"
  fullscreen: true

# view icon config
flutter_icons:
  image_path: "assets/images/AINavi.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    # 音声
    - assets/records/
    # 環境変数
    - assets/.env
    # chatAI用画像
    - assets/images/chatCorrection.png
    - assets/images/chatQuestion.png
